### ISSUE TITLE
Some functions not working

### ISSUE THREAD

**Issue by itwasabhi** [uArm-Developer/UArmForPython#1]
I tried running some of the functions and the program kept getting hung...

readAngle and writeAngle don't seem to work, so when I try to attach all servos using uarmAttach(), the program gets stuck on line 82. 

I was able workaround by manually attaching each servo and setting the uarm_status=1. With this, I'm able to use writeServoAngle() and  moveTo(), but still not able to use writeAngle or readAngle().

**Comment by songjunyi** [comment]
Hi, have you add pyfirmata-uarm library with UarmForPython and calibrated uarm?

**Comment by itwasabhi** [comment]
Yea, I finished all the installation steps. I'm guessing the other functions wouldn't work at all unless the library was properly installed anyway.
