### ISSUE TITLE
Error while trying to import UArm

### ISSUE THREAD

**Issue by redsandman74** [uArm-Developer/UArmForPython#2]
Hi,
I was trying to use the arm via Python in Anaconda, but I had the following  error:

[Anaconda3] C:\Users\xxx>python
Python 3.5.1 |Anaconda 2.4.1 (64-bit)| (default, Jan 29 2016, 15:01:46) [MSC v.1
900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

> > > from UArmForPython.uarm_python import Uarm
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "C:\Users\xxx\AppData\Local\Continuum\Anaconda3\lib\site-packages\u
> > > armforpython-1.0.1-py3.5.egg\UArmForPython\uarm_python.py", line 220
> > >     g_l5 = (MATH_L2 + MATH_L3_math.cos(theta_2 / MATH_TRANS) + MATH_L4_math.cos(
> > > theta_3 / MATH_TRANS));

```
                  ^
```

TabError: inconsistent use of tabs and spaces in indentation

**Comment by altjz** [comment]
@redsandman74 Hi, This is Alex from uArm Team, I checked your error log, Your python version is 3.5.1, unfortunately the uarm4python lib doesn't support python 3.x.

**Comment by redsandman74** [comment]
Thank you Alex, I'm going correct it.
