### ISSUE TITLE
Weird position after calibration 

### ISSUE THREAD

**Issue by yilinjuang** [uArm-Developer/UArmForPython#5]
After I enter Y to confirm in pyuarm.tools.calibrate step 2, uArm automatic move to another place in step 3. Then, I read the coordinate using `uArm.read_coordinate()`. The output is `[-6.38, -6.64, 19.32]`. Did I calibrate it in the right way? Following is the log of step 3.

```
3.0. Clearing Stretch Completed Flag in EEPROM.
3. Start Calibrate Stretch Offset
3.0 Moving uArm to Correct Place
minAngle_L: 457
minAngle_R: 118
initPosL: 126
initPosL: 125
initPosL: 124
initPosL: 123
    3.1 Saving Stretch Offset into EEPROM
    3.2 Mark Completed Flag in EEPROM
-13 -9
Calibration DONE!!
```

**Comment by altjz** [comment]
hi @frankyjuang , I increase the calibration points, (original 16, Now 120). Please update the pyuarm. `pip install pyuarm --U`
