### ISSUE TITLE
detach_all_servos

### ISSUE THREAD

**Issue by mairasaboia** [uArm-Developer/UArmForPython#6]
After I updated the firmware to version 1.7.2, the function  detach_all_servos() is not working anymore. None servo was detached.

**Comment by altjz** [comment]
hi @mairasaboia , did you upgrade the pyuarm? 1.3.26 might fix the issue. Please use `pip install pyuarm --U`

**Comment by mairasaboia** [comment]
Thank you Alex, now it's working. 

The firmware installed is the 1.7.3:

$ python -m pyuarm.tools.firmware_helper
Reading Firmware version from uArm...
Initialize uArm, port is /dev/ttyUSB0...
Latest Firmware version: 1.7.3 

However, when I initialize the uarm, it says that the firmware is 1.7.2

> > > Initialize uArm, port is /dev/ttyUSB0...
> > > Firmware Version: 1.7.2

Anyway, it's working :D 
Thanks!

mss

**Comment by altjz** [comment]
Sorry, I forget to update the version inside.
