### ISSUE TITLE
Error in read_coordinate() after move_to() with time_spend >=5

### ISSUE THREAD

**Issue by mairasaboia** [uArm-Developer/UArmForPython#7]
Hello,

I have this small procedure:

> > > uarm = pyuarm.uArm()
> > > uarm.attach_all_servos()
> > > uarm.move_to(-9,-5,10, time_spend=5)
> > > print uarm.read_coordinate()
> > > uarm.detach_all_servos()

and every time that I set the "time_spend" (for the function move_to(..))  greater or equal to 5 I get the following error, but only if I use the read_coordinate() just after the calling.

![error](https://cloud.githubusercontent.com/assets/11801056/16699312/711ad398-4521-11e6-8c7d-575f42454e96.png)
I don't know if I should report issues here or if I should use the uFactory forum, please let me know.

-- Mss

**Comment by diogoalmeida** [comment]
Hello, 

I am facing the same issue, have you found a good solution? A hack to prevent this problem is to sleep `time_spend - 5` seconds before calling the read_coordinate method, but there should be a better way.

**Comment by altjz** [comment]
fix with [0b6f95](https://github.com/uArm-Developer/pyuarm/commit/0b6f9502da4377f6efb9a3356985558a7671bdec)
